inherit_from: .rubocop-todo.yml

Encoding:
  Enabled: false
  # EnforcedStyle: when_needed

AllCops:
  Include:
    - Guardfile
    - Rakefile
    - pacto.gemspec
  Exclude:
    - bin/**/*
    - tmp/**/*
    - tmp/**/*.rb
    - samples/tests/polytrix/generators/**/*
