language: ruby
before_install:
 # Travis has gradle on the java worker but not the ruby worker
 - sudo add-apt-repository -y ppa:cwchien/gradle
 - sudo apt-get update -qq
 - sudo apt-get install -qq gradle
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  # - jruby # Not currently supported, because mixlib/shellout doesn't support jruby

